language: cpp
compiler:
- gcc
- clang

script: mkdir build && cd build && cmake ../ && make

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#scidb-vistas"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
