// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "VISTAS.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <boost/tr1/memory.hpp>
#include <vistas/vistas.h>
#include <SHP3D.h>
#include <Envision.h>
#include <ESRIGridASCII.h>
#include <TerrainAndColor.h>
#include <vector>
#include <stdexcept>
#include <algorithm>
#include <set>

#ifdef MACOSX
const VI_String DATA_PREFIX = VI_String("/Users/ratanasv/Documents/data/");
#else
const VI_String DATA_PREFIX = VI_String("/home/ubuntu/data/");
#endif
const VI_String SHP_EXTENSION = VI_String("shp");
const VI_String ESRIGRIDASCII_EXTENSION = VI_String("asc");

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using std::tr1::shared_ptr;
using std::vector;
using std::find_if;
using std::set;
using std::runtime_error;
using namespace  ::servis;
using std::pair;

class FindIfExtension {
private:
    const VI_String extension;
public:
    FindIfExtension(const VI_String& in) : extension(in) {};
    bool operator() (const VI_Path& element) {
        return element.GetExtension() == extension;
    }
};


class VISTASHandler : virtual public VISTASIf {
public:
	typedef pair<shared_ptr<VI_DataPlugin>, shared_ptr<VI_VizPlugin3D>> PluginPair;
	VISTASHandler() {
		// Your initialization goes here
	}

	PluginPair getPlugins(const std::string& fileName) {
		shared_ptr<VI_DataPlugin> dataPlugin;
		shared_ptr<VI_VizPlugin3D> vizPlugin;
		const VI_Path pathToFile = VI_Path(DATA_PREFIX + VI_String(fileName));
		auto datasetsList = pathToFile.GetFiles();
		auto foundFile = find_if(datasetsList.begin(), datasetsList.end(), FindIfExtension(SHP_EXTENSION));
		if (foundFile != datasetsList.end()) {
			
			dataPlugin.reset(new EnvisionDataPlugin());
			dataPlugin->Set(*foundFile);
			vizPlugin.reset(new SHP3D());
			vizPlugin->SetData(dataPlugin.get(), 0);
		} else {
			foundFile = find_if(datasetsList.begin(), datasetsList.end(), [](const VI_Path& path) {
				bool isDEM = path.GetElement(-1).Find(VI_String("DEM")) != -1;
				return path.GetExtension() == ESRIGRIDASCII_EXTENSION && !isDEM;
			});
			dataPlugin.reset(new ESRIGridPlugin());
			dataPlugin->Set(*foundFile);
			
			auto demFile = find_if(datasetsList.begin(), datasetsList.end(), [](const VI_Path& path) {
				bool isDEM = path.GetElement(-1).Find(VI_String("DEM")) != -1;
				return path.GetExtension() == ESRIGRIDASCII_EXTENSION && isDEM;
			});
			shared_ptr<VI_DataPlugin> demPlugin(new ESRIGridPlugin());
			demPlugin->Set(*demFile);

			vizPlugin.reset(new TerrainPlugin());
			vizPlugin->SetData(demPlugin.get(), 0); //for DEM
			vizPlugin->SetData(dataPlugin.get(), 1);
		}
		return PluginPair(dataPlugin, vizPlugin);
	}

	virtual void getTerrain(Terrain& _return, const std::string& fileName) {
		// Your implementation goes here
		printf("getTerrain %s\n", fileName.c_str());
		auto plugins = getPlugins(fileName);
		auto vizPlugin = plugins.second;
		auto dataPlugin = plugins.first;
		auto shapeMesh = vizPlugin->GetMesh();
		auto vertexCount = shapeMesh.GetVertexCount();
		auto indexCount = shapeMesh.GetIndexCount();

		_return.vertices.reserve(vertexCount);
		float* vertexPtr = shapeMesh.AcquireVertexArray();
		for (int i=0; i<vertexCount; i++) {
			double x = (double)vertexPtr[3*i+0];
			double y = (double)vertexPtr[3*i+1];
			double z = (double)vertexPtr[3*i+2];
			_return.vertices.push_back(V3(x,y,z));
		}
		shapeMesh.ReleaseVertexArray();


		_return.indices.reserve(indexCount);
		unsigned* indexPtr = shapeMesh.AcquireIndexArray();
		for (int i=0; i<indexCount; i++) {
			_return.indices.push_back((int32_t) indexPtr[i]);
		}
		shapeMesh.ReleaseIndexArray();
	}

	virtual void getColor(std::vector<V3> & _return, const std::string& fileName, const std::string& attribute) {
		// Your implementation goes here
		printf("getColor %s %s \n", fileName.c_str(), attribute.c_str());
		auto plugins = getPlugins(fileName);
		auto vizPlugin = std::tr1::dynamic_pointer_cast<SHP3D>(plugins.second);
		vizPlugin->SetAttribute(attribute);

		auto shapeMesh = vizPlugin->GetMesh();
		auto vertexCount = shapeMesh.GetVertexCount();

		_return.reserve(vertexCount);
		float* colorPtr = shapeMesh.AcquireColorArray();
		for (int i=0; i<vertexCount; i++) {
			double x = (double)colorPtr[3*i+0];
			double y = (double)colorPtr[3*i+1];
			double z = (double)colorPtr[3*i+2];
			_return.push_back(V3(x,y,z));
		}
		shapeMesh.ReleaseColorArray();

	}

	virtual void getNormalMap(Texture& _return, const std::string& fileName) {
		// Your implementation goes here
		printf("getNormalMap\n %s", fileName.c_str());
	}

	virtual void getTextureMap(Texture& _return, const std::string& fileName, const std::string& attribute) {
		// Your implementation goes here
		printf("getTextureMap\n %s %s", fileName.c_str(), attribute.c_str());
	}

	virtual void getAttributes(std::vector<std::string> & _return, const std::string& fileName) {
		printf("getAttributes %s \n", fileName.c_str());
		shared_ptr<VI_DataPlugin> dataPlugin;
		const VI_Path pathToFile = VI_Path(DATA_PREFIX + VI_String(fileName));
		auto datasetsList = pathToFile.GetFiles();
        auto foundFile = find_if(datasetsList.begin(), datasetsList.end(), FindIfExtension(SHP_EXTENSION));
        if (foundFile != datasetsList.end()) {
            dataPlugin.reset(new EnvisionDataPlugin());
        } else {
            dataPlugin.reset();
			throw runtime_error("velma plugin not supported");
        }
		dataPlugin->Set(*foundFile);
		auto attributeList = dataPlugin->GetAttributes();
		_return.insert(_return.begin(), attributeList.begin(), attributeList.end());
	}

	virtual void getDatasets(std::vector<std::string> & _return) {
		printf("getDatasets\n");
		VI_Path datasetsRoot(DATA_PREFIX);
		auto datasetsList = datasetsRoot.GetFiles();
		for (auto it : datasetsList) {
			_return.push_back(it.GetElement(-1).c_str());
		}
	}

};

int main(int argc, char **argv) {
	int port = 9090;
	shared_ptr<VISTASHandler> handler(new VISTASHandler());
	shared_ptr<TProcessor> processor(new VISTASProcessor(handler));
	shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
#ifdef MACOSX
	shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
#else
	shared_ptr<TTransportFactory> transportFactory(new TFramedTransportFactory());
#endif
	shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

	TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
	server.serve();
	return 0;
}

