//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./servis_types');
//HELPER FUNCTIONS AND STRUCTURES

VISTAS_getTerrain_args = function(args) {
  this.fileName = null;
  if (args) {
    if (args.fileName !== undefined) {
      this.fileName = args.fileName;
    }
  }
};
VISTAS_getTerrain_args.prototype = {};
VISTAS_getTerrain_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.fileName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

VISTAS_getTerrain_args.prototype.write = function(output) {
  output.writeStructBegin('VISTAS_getTerrain_args');
  if (this.fileName !== null && this.fileName !== undefined) {
    output.writeFieldBegin('fileName', Thrift.Type.STRING, 1);
    output.writeString(this.fileName);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

VISTAS_getTerrain_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
VISTAS_getTerrain_result.prototype = {};
VISTAS_getTerrain_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Terrain();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

VISTAS_getTerrain_result.prototype.write = function(output) {
  output.writeStructBegin('VISTAS_getTerrain_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

VISTASClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
VISTASClient.prototype = {};
VISTASClient.prototype.getTerrain = function(fileName, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getTerrain(fileName);
};

VISTASClient.prototype.send_getTerrain = function(fileName) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getTerrain', Thrift.MessageType.CALL, this.seqid);
  var args = new VISTAS_getTerrain_args();
  args.fileName = fileName;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

VISTASClient.prototype.recv_getTerrain = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new VISTAS_getTerrain_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getTerrain failed: unknown result');
};
VISTASProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
VISTASProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

VISTASProcessor.prototype.process_getTerrain = function(seqid, input, output) {
  var args = new VISTAS_getTerrain_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.getTerrain(args.fileName, function (err, result) {
    var result = new VISTAS_getTerrain_result((err != null ? err : {success: result}));
    output.writeMessageBegin("getTerrain", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

