/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "servis_constants.h"

namespace servis {

const servisConstants g_servis_constants;

servisConstants::servisConstants() {
}

} // namespace

