/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef servis_CONSTANTS_H
#define servis_CONSTANTS_H

#include "servis_types.h"

namespace servis {

class servisConstants {
 public:
  servisConstants();

};

extern const servisConstants g_servis_constants;

} // namespace

#endif
