/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef VISTAS_H
#define VISTAS_H

#include <thrift/TDispatchProcessor.h>
#include "servis_types.h"

namespace servis {

class VISTASIf {
 public:
  virtual ~VISTASIf() {}
  virtual void getTerrain(Terrain& _return, const std::string& fileName) = 0;
  virtual void getColor(std::vector<V3> & _return, const std::string& fileName, const std::string& attribute) = 0;
  virtual void getNormalMap(Texture& _return, const std::string& fileName) = 0;
  virtual void getTextureMap(Texture& _return, const std::string& fileName, const std::string& attribute) = 0;
  virtual void getAttributes(std::vector<std::string> & _return, const std::string& fileName) = 0;
  virtual void getDatasets(std::vector<std::string> & _return) = 0;
};

class VISTASIfFactory {
 public:
  typedef VISTASIf Handler;

  virtual ~VISTASIfFactory() {}

  virtual VISTASIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(VISTASIf* /* handler */) = 0;
};

class VISTASIfSingletonFactory : virtual public VISTASIfFactory {
 public:
  VISTASIfSingletonFactory(const boost::shared_ptr<VISTASIf>& iface) : iface_(iface) {}
  virtual ~VISTASIfSingletonFactory() {}

  virtual VISTASIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(VISTASIf* /* handler */) {}

 protected:
  boost::shared_ptr<VISTASIf> iface_;
};

class VISTASNull : virtual public VISTASIf {
 public:
  virtual ~VISTASNull() {}
  void getTerrain(Terrain& /* _return */, const std::string& /* fileName */) {
    return;
  }
  void getColor(std::vector<V3> & /* _return */, const std::string& /* fileName */, const std::string& /* attribute */) {
    return;
  }
  void getNormalMap(Texture& /* _return */, const std::string& /* fileName */) {
    return;
  }
  void getTextureMap(Texture& /* _return */, const std::string& /* fileName */, const std::string& /* attribute */) {
    return;
  }
  void getAttributes(std::vector<std::string> & /* _return */, const std::string& /* fileName */) {
    return;
  }
  void getDatasets(std::vector<std::string> & /* _return */) {
    return;
  }
};

typedef struct _VISTAS_getTerrain_args__isset {
  _VISTAS_getTerrain_args__isset() : fileName(false) {}
  bool fileName;
} _VISTAS_getTerrain_args__isset;

class VISTAS_getTerrain_args {
 public:

  VISTAS_getTerrain_args() : fileName() {
  }

  virtual ~VISTAS_getTerrain_args() throw() {}

  std::string fileName;

  _VISTAS_getTerrain_args__isset __isset;

  void __set_fileName(const std::string& val) {
    fileName = val;
  }

  bool operator == (const VISTAS_getTerrain_args & rhs) const
  {
    if (!(fileName == rhs.fileName))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getTerrain_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getTerrain_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VISTAS_getTerrain_pargs {
 public:


  virtual ~VISTAS_getTerrain_pargs() throw() {}

  const std::string* fileName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getTerrain_result__isset {
  _VISTAS_getTerrain_result__isset() : success(false) {}
  bool success;
} _VISTAS_getTerrain_result__isset;

class VISTAS_getTerrain_result {
 public:

  VISTAS_getTerrain_result() {
  }

  virtual ~VISTAS_getTerrain_result() throw() {}

  Terrain success;

  _VISTAS_getTerrain_result__isset __isset;

  void __set_success(const Terrain& val) {
    success = val;
  }

  bool operator == (const VISTAS_getTerrain_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getTerrain_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getTerrain_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getTerrain_presult__isset {
  _VISTAS_getTerrain_presult__isset() : success(false) {}
  bool success;
} _VISTAS_getTerrain_presult__isset;

class VISTAS_getTerrain_presult {
 public:


  virtual ~VISTAS_getTerrain_presult() throw() {}

  Terrain* success;

  _VISTAS_getTerrain_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _VISTAS_getColor_args__isset {
  _VISTAS_getColor_args__isset() : fileName(false), attribute(false) {}
  bool fileName;
  bool attribute;
} _VISTAS_getColor_args__isset;

class VISTAS_getColor_args {
 public:

  VISTAS_getColor_args() : fileName(), attribute() {
  }

  virtual ~VISTAS_getColor_args() throw() {}

  std::string fileName;
  std::string attribute;

  _VISTAS_getColor_args__isset __isset;

  void __set_fileName(const std::string& val) {
    fileName = val;
  }

  void __set_attribute(const std::string& val) {
    attribute = val;
  }

  bool operator == (const VISTAS_getColor_args & rhs) const
  {
    if (!(fileName == rhs.fileName))
      return false;
    if (!(attribute == rhs.attribute))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getColor_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getColor_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VISTAS_getColor_pargs {
 public:


  virtual ~VISTAS_getColor_pargs() throw() {}

  const std::string* fileName;
  const std::string* attribute;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getColor_result__isset {
  _VISTAS_getColor_result__isset() : success(false) {}
  bool success;
} _VISTAS_getColor_result__isset;

class VISTAS_getColor_result {
 public:

  VISTAS_getColor_result() {
  }

  virtual ~VISTAS_getColor_result() throw() {}

  std::vector<V3>  success;

  _VISTAS_getColor_result__isset __isset;

  void __set_success(const std::vector<V3> & val) {
    success = val;
  }

  bool operator == (const VISTAS_getColor_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getColor_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getColor_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getColor_presult__isset {
  _VISTAS_getColor_presult__isset() : success(false) {}
  bool success;
} _VISTAS_getColor_presult__isset;

class VISTAS_getColor_presult {
 public:


  virtual ~VISTAS_getColor_presult() throw() {}

  std::vector<V3> * success;

  _VISTAS_getColor_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _VISTAS_getNormalMap_args__isset {
  _VISTAS_getNormalMap_args__isset() : fileName(false) {}
  bool fileName;
} _VISTAS_getNormalMap_args__isset;

class VISTAS_getNormalMap_args {
 public:

  VISTAS_getNormalMap_args() : fileName() {
  }

  virtual ~VISTAS_getNormalMap_args() throw() {}

  std::string fileName;

  _VISTAS_getNormalMap_args__isset __isset;

  void __set_fileName(const std::string& val) {
    fileName = val;
  }

  bool operator == (const VISTAS_getNormalMap_args & rhs) const
  {
    if (!(fileName == rhs.fileName))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getNormalMap_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getNormalMap_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VISTAS_getNormalMap_pargs {
 public:


  virtual ~VISTAS_getNormalMap_pargs() throw() {}

  const std::string* fileName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getNormalMap_result__isset {
  _VISTAS_getNormalMap_result__isset() : success(false) {}
  bool success;
} _VISTAS_getNormalMap_result__isset;

class VISTAS_getNormalMap_result {
 public:

  VISTAS_getNormalMap_result() {
  }

  virtual ~VISTAS_getNormalMap_result() throw() {}

  Texture success;

  _VISTAS_getNormalMap_result__isset __isset;

  void __set_success(const Texture& val) {
    success = val;
  }

  bool operator == (const VISTAS_getNormalMap_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getNormalMap_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getNormalMap_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getNormalMap_presult__isset {
  _VISTAS_getNormalMap_presult__isset() : success(false) {}
  bool success;
} _VISTAS_getNormalMap_presult__isset;

class VISTAS_getNormalMap_presult {
 public:


  virtual ~VISTAS_getNormalMap_presult() throw() {}

  Texture* success;

  _VISTAS_getNormalMap_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _VISTAS_getTextureMap_args__isset {
  _VISTAS_getTextureMap_args__isset() : fileName(false), attribute(false) {}
  bool fileName;
  bool attribute;
} _VISTAS_getTextureMap_args__isset;

class VISTAS_getTextureMap_args {
 public:

  VISTAS_getTextureMap_args() : fileName(), attribute() {
  }

  virtual ~VISTAS_getTextureMap_args() throw() {}

  std::string fileName;
  std::string attribute;

  _VISTAS_getTextureMap_args__isset __isset;

  void __set_fileName(const std::string& val) {
    fileName = val;
  }

  void __set_attribute(const std::string& val) {
    attribute = val;
  }

  bool operator == (const VISTAS_getTextureMap_args & rhs) const
  {
    if (!(fileName == rhs.fileName))
      return false;
    if (!(attribute == rhs.attribute))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getTextureMap_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getTextureMap_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VISTAS_getTextureMap_pargs {
 public:


  virtual ~VISTAS_getTextureMap_pargs() throw() {}

  const std::string* fileName;
  const std::string* attribute;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getTextureMap_result__isset {
  _VISTAS_getTextureMap_result__isset() : success(false) {}
  bool success;
} _VISTAS_getTextureMap_result__isset;

class VISTAS_getTextureMap_result {
 public:

  VISTAS_getTextureMap_result() {
  }

  virtual ~VISTAS_getTextureMap_result() throw() {}

  Texture success;

  _VISTAS_getTextureMap_result__isset __isset;

  void __set_success(const Texture& val) {
    success = val;
  }

  bool operator == (const VISTAS_getTextureMap_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getTextureMap_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getTextureMap_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getTextureMap_presult__isset {
  _VISTAS_getTextureMap_presult__isset() : success(false) {}
  bool success;
} _VISTAS_getTextureMap_presult__isset;

class VISTAS_getTextureMap_presult {
 public:


  virtual ~VISTAS_getTextureMap_presult() throw() {}

  Texture* success;

  _VISTAS_getTextureMap_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _VISTAS_getAttributes_args__isset {
  _VISTAS_getAttributes_args__isset() : fileName(false) {}
  bool fileName;
} _VISTAS_getAttributes_args__isset;

class VISTAS_getAttributes_args {
 public:

  VISTAS_getAttributes_args() : fileName() {
  }

  virtual ~VISTAS_getAttributes_args() throw() {}

  std::string fileName;

  _VISTAS_getAttributes_args__isset __isset;

  void __set_fileName(const std::string& val) {
    fileName = val;
  }

  bool operator == (const VISTAS_getAttributes_args & rhs) const
  {
    if (!(fileName == rhs.fileName))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getAttributes_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getAttributes_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VISTAS_getAttributes_pargs {
 public:


  virtual ~VISTAS_getAttributes_pargs() throw() {}

  const std::string* fileName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getAttributes_result__isset {
  _VISTAS_getAttributes_result__isset() : success(false) {}
  bool success;
} _VISTAS_getAttributes_result__isset;

class VISTAS_getAttributes_result {
 public:

  VISTAS_getAttributes_result() {
  }

  virtual ~VISTAS_getAttributes_result() throw() {}

  std::vector<std::string>  success;

  _VISTAS_getAttributes_result__isset __isset;

  void __set_success(const std::vector<std::string> & val) {
    success = val;
  }

  bool operator == (const VISTAS_getAttributes_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getAttributes_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getAttributes_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getAttributes_presult__isset {
  _VISTAS_getAttributes_presult__isset() : success(false) {}
  bool success;
} _VISTAS_getAttributes_presult__isset;

class VISTAS_getAttributes_presult {
 public:


  virtual ~VISTAS_getAttributes_presult() throw() {}

  std::vector<std::string> * success;

  _VISTAS_getAttributes_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class VISTAS_getDatasets_args {
 public:

  VISTAS_getDatasets_args() {
  }

  virtual ~VISTAS_getDatasets_args() throw() {}


  bool operator == (const VISTAS_getDatasets_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const VISTAS_getDatasets_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getDatasets_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class VISTAS_getDatasets_pargs {
 public:


  virtual ~VISTAS_getDatasets_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getDatasets_result__isset {
  _VISTAS_getDatasets_result__isset() : success(false) {}
  bool success;
} _VISTAS_getDatasets_result__isset;

class VISTAS_getDatasets_result {
 public:

  VISTAS_getDatasets_result() {
  }

  virtual ~VISTAS_getDatasets_result() throw() {}

  std::vector<std::string>  success;

  _VISTAS_getDatasets_result__isset __isset;

  void __set_success(const std::vector<std::string> & val) {
    success = val;
  }

  bool operator == (const VISTAS_getDatasets_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const VISTAS_getDatasets_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VISTAS_getDatasets_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _VISTAS_getDatasets_presult__isset {
  _VISTAS_getDatasets_presult__isset() : success(false) {}
  bool success;
} _VISTAS_getDatasets_presult__isset;

class VISTAS_getDatasets_presult {
 public:


  virtual ~VISTAS_getDatasets_presult() throw() {}

  std::vector<std::string> * success;

  _VISTAS_getDatasets_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class VISTASClient : virtual public VISTASIf {
 public:
  VISTASClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  VISTASClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getTerrain(Terrain& _return, const std::string& fileName);
  void send_getTerrain(const std::string& fileName);
  void recv_getTerrain(Terrain& _return);
  void getColor(std::vector<V3> & _return, const std::string& fileName, const std::string& attribute);
  void send_getColor(const std::string& fileName, const std::string& attribute);
  void recv_getColor(std::vector<V3> & _return);
  void getNormalMap(Texture& _return, const std::string& fileName);
  void send_getNormalMap(const std::string& fileName);
  void recv_getNormalMap(Texture& _return);
  void getTextureMap(Texture& _return, const std::string& fileName, const std::string& attribute);
  void send_getTextureMap(const std::string& fileName, const std::string& attribute);
  void recv_getTextureMap(Texture& _return);
  void getAttributes(std::vector<std::string> & _return, const std::string& fileName);
  void send_getAttributes(const std::string& fileName);
  void recv_getAttributes(std::vector<std::string> & _return);
  void getDatasets(std::vector<std::string> & _return);
  void send_getDatasets();
  void recv_getDatasets(std::vector<std::string> & _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class VISTASProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<VISTASIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (VISTASProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getTerrain(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getColor(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getNormalMap(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getTextureMap(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getAttributes(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getDatasets(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  VISTASProcessor(boost::shared_ptr<VISTASIf> iface) :
    iface_(iface) {
    processMap_["getTerrain"] = &VISTASProcessor::process_getTerrain;
    processMap_["getColor"] = &VISTASProcessor::process_getColor;
    processMap_["getNormalMap"] = &VISTASProcessor::process_getNormalMap;
    processMap_["getTextureMap"] = &VISTASProcessor::process_getTextureMap;
    processMap_["getAttributes"] = &VISTASProcessor::process_getAttributes;
    processMap_["getDatasets"] = &VISTASProcessor::process_getDatasets;
  }

  virtual ~VISTASProcessor() {}
};

class VISTASProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  VISTASProcessorFactory(const ::boost::shared_ptr< VISTASIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< VISTASIfFactory > handlerFactory_;
};

class VISTASMultiface : virtual public VISTASIf {
 public:
  VISTASMultiface(std::vector<boost::shared_ptr<VISTASIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~VISTASMultiface() {}
 protected:
  std::vector<boost::shared_ptr<VISTASIf> > ifaces_;
  VISTASMultiface() {}
  void add(boost::shared_ptr<VISTASIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getTerrain(Terrain& _return, const std::string& fileName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getTerrain(_return, fileName);
    }
    ifaces_[i]->getTerrain(_return, fileName);
    return;
  }

  void getColor(std::vector<V3> & _return, const std::string& fileName, const std::string& attribute) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getColor(_return, fileName, attribute);
    }
    ifaces_[i]->getColor(_return, fileName, attribute);
    return;
  }

  void getNormalMap(Texture& _return, const std::string& fileName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getNormalMap(_return, fileName);
    }
    ifaces_[i]->getNormalMap(_return, fileName);
    return;
  }

  void getTextureMap(Texture& _return, const std::string& fileName, const std::string& attribute) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getTextureMap(_return, fileName, attribute);
    }
    ifaces_[i]->getTextureMap(_return, fileName, attribute);
    return;
  }

  void getAttributes(std::vector<std::string> & _return, const std::string& fileName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getAttributes(_return, fileName);
    }
    ifaces_[i]->getAttributes(_return, fileName);
    return;
  }

  void getDatasets(std::vector<std::string> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getDatasets(_return);
    }
    ifaces_[i]->getDatasets(_return);
    return;
  }

};

} // namespace

#endif
